spring:
  application:
    name: spring-boot-eureka-client-rest-api


server:
  port: 8083

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka